var labels = {

	"en":{
		"doing":"What are you doing?",
		"me_tab_link":"Me",
		"friends_tab_link":"Friends",
		"followers_tab_link":"Followers",
		"clear":"Clear",
		"update":"Update",
		"newer":"Newer",
		"older":"Older",
		"log_out":"Log out",
		"sign_in":"Sign in",
		"written":"Written on ",
		"alas":"",
		"by":"by",
		"shorten_error":"Sorry, an error has ocurried and the URL could not be shortened.",
		"error_from_bitly":"Error from Bit.ly service: ",
		"without_api_key":"Sorry, there is not bitly API KEY. The URLs cannot be shortened.",
		"http_error":"Sorry, an error has ocurried and now we cannot send your request.</br>Please, sign in again and try it again...",
		"update_error":"Sorry, the Twitter service is temporarily unavailable.",
		"duplicated_message_error":"Sorry, the sent message is duplicated. The message has not been posted.",
		"long_message_error":"Sorry, the message is too long and has not been posted. Remove some characteres and try it again.",
		"set_username":"Please, set your username in Twitter using the preferences.",
		"send_error": "Sorry, we cannot send your request, check what could be wrong in your message (too long, strange characters, ...)"
		},

	"es":{
		"doing":"&iquest;Qu&eacute; est&aacute;s haciendo?",
		"me_tab_link":"Yo",
		"friends_tab_link":"Amigos",
		"followers_tab_link":"Seguidores",
		"clear":"Borrar",
		"update":"Actualizar",
		"newer":"Recientes",
		"older":"Antiguos",
		"log_out":"Salir",
		"sign_in":"Acceder",
		"written":"Escrito el ",
		"alas":" a las ",
		"by":"por",
		"shorten_error":"Lo sentimos, ha ocurrido un error y la direccion web no se ha podido acortar.",
		"error_from_bitly":"Error del servicio Bit.ly: ",
		"without_api_key":"Lo sentimos, no se encuentra la API KEY para el servicio bitly. Las direcciones web no se pueden acortar.",
		"http_error": "Lo sentimos, ha ocurrido un error y no hemos podido realizar su petici&oacute;n.</br>Por favor, reg&iacute;strese de nuevo y vuelva a intentarlo...",
		"update_error":"Lo sentimos, el servicios de Twitter no est&aacute; disponible temporalmente.",
		"duplicated_message_error":"Lo sentimos, el mensaje que intenta enviar est&aacute; repetido y no ha sido publicado.",
		"long_message_error":"Lo sentimos, el mensaje es demasiado largo. Modif&iacute;quelo antes de enviarlo.",
		"set_username":"Por favor, introduzca su nombre de usuario y contrase&ntilde;a de Twitter usando las preferencias.",
		"send_error": "Lo sentimos, no hemos podido realizar su petici&oacute;n. Compruebe que el mensaje sea correcto (longitud, caracteres extra&ntilde;os, ...)"		
		}
};