var labels = {"en":{"si":"yes",
                    "titulomodificar":"Edit task",
                    "prueba":"test",
                    "barHeader":"Add task",
                    "barHeaderHidden":"Hidden",                    
                    "tareal":"ToDo",
                    "modificar":"Edit",
                    "tituloenviar":"Send task",
                    "fechal":"Date",
                    "ocultar":"Hide",
                    "categoria":"Category",
                    "tituloeliminar":"Remove task",
                    "addtask":"Add task",
                    "seleccionarFecha":"Select Date",
                    "addButton":"Add"},
              "es":{"si":"si",
                    "titulomodificar":"Modificar tarea",
                    "prueba":"prueba",
                    "barHeader":"Añadir tarea",
                    "barHeaderHidden":"Ocultar",                                        
                    "tareal":"Tarea",
                    "modificar":"Modificar",
                    "tituloenviar":"Enviar tarea",
                    "fechal":"Fecha",
                    "ocultar":"Ocultar",
                    "categoria":"Categoría",
                    "tituloeliminar":"Eliminar tarea",
                    "addtask":"Añadir tarea",
                    "seleccionarFecha":"Seleccionar Fecha",
                    "addButton":"Añadir"}
              };
